// Code generated by ent, DO NOT EDIT.

package invoicepublicreference

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicepublicreference type in the database.
	Label = "invoice_public_reference"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldPublicReference holds the string denoting the public_reference field in the database.
	FieldPublicReference = "public_reference"
	// FieldReservationKey holds the string denoting the reservation_key field in the database.
	FieldReservationKey = "reservation_key"
	// FieldInvoiceID holds the string denoting the invoice_id field in the database.
	FieldInvoiceID = "invoice_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldBoundAt holds the string denoting the bound_at field in the database.
	FieldBoundAt = "bound_at"
	// Table holds the table name of the invoicepublicreference in the database.
	Table = "invoice_public_references"
)

// Columns holds all SQL columns for invoicepublicreference fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEnvironmentID,
	FieldPublicReference,
	FieldReservationKey,
	FieldInvoiceID,
	FieldCustomerID,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldBoundAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// EnvironmentIDValidator is a validator for the "environment_id" field. It is called by the builders before save.
	EnvironmentIDValidator func(string) error
	// PublicReferenceValidator is a validator for the "public_reference" field. It is called by the builders before save.
	PublicReferenceValidator func(string) error
	// ReservationKeyValidator is a validator for the "reservation_key" field. It is called by the builders before save.
	ReservationKeyValidator func(string) error
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoicePublicReference queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByPublicReference orders the results by the public_reference field.
func ByPublicReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicReference, opts...).ToFunc()
}

// ByReservationKey orders the results by the reservation_key field.
func ByReservationKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationKey, opts...).ToFunc()
}

// ByInvoiceID orders the results by the invoice_id field.
func ByInvoiceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvoiceID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBoundAt orders the results by the bound_at field.
func ByBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAt, opts...).ToFunc()
}
