// Code generated by ent, DO NOT EDIT.

package invoicepublicreference

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldTenantID, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldEnvironmentID, v))
}

// PublicReference applies equality check predicate on the "public_reference" field. It's identical to PublicReferenceEQ.
func PublicReference(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldPublicReference, v))
}

// ReservationKey applies equality check predicate on the "reservation_key" field. It's identical to ReservationKeyEQ.
func ReservationKey(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldReservationKey, v))
}

// InvoiceID applies equality check predicate on the "invoice_id" field. It's identical to InvoiceIDEQ.
func InvoiceID(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldInvoiceID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCustomerID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCreatedAt, v))
}

// BoundAt applies equality check predicate on the "bound_at" field. It's identical to BoundAtEQ.
func BoundAt(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldBoundAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldTenantID, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// PublicReferenceEQ applies the EQ predicate on the "public_reference" field.
func PublicReferenceEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldPublicReference, v))
}

// PublicReferenceNEQ applies the NEQ predicate on the "public_reference" field.
func PublicReferenceNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldPublicReference, v))
}

// PublicReferenceIn applies the In predicate on the "public_reference" field.
func PublicReferenceIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldPublicReference, vs...))
}

// PublicReferenceNotIn applies the NotIn predicate on the "public_reference" field.
func PublicReferenceNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldPublicReference, vs...))
}

// PublicReferenceGT applies the GT predicate on the "public_reference" field.
func PublicReferenceGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldPublicReference, v))
}

// PublicReferenceGTE applies the GTE predicate on the "public_reference" field.
func PublicReferenceGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldPublicReference, v))
}

// PublicReferenceLT applies the LT predicate on the "public_reference" field.
func PublicReferenceLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldPublicReference, v))
}

// PublicReferenceLTE applies the LTE predicate on the "public_reference" field.
func PublicReferenceLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldPublicReference, v))
}

// PublicReferenceContains applies the Contains predicate on the "public_reference" field.
func PublicReferenceContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldPublicReference, v))
}

// PublicReferenceHasPrefix applies the HasPrefix predicate on the "public_reference" field.
func PublicReferenceHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldPublicReference, v))
}

// PublicReferenceHasSuffix applies the HasSuffix predicate on the "public_reference" field.
func PublicReferenceHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldPublicReference, v))
}

// PublicReferenceEqualFold applies the EqualFold predicate on the "public_reference" field.
func PublicReferenceEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldPublicReference, v))
}

// PublicReferenceContainsFold applies the ContainsFold predicate on the "public_reference" field.
func PublicReferenceContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldPublicReference, v))
}

// ReservationKeyEQ applies the EQ predicate on the "reservation_key" field.
func ReservationKeyEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldReservationKey, v))
}

// ReservationKeyNEQ applies the NEQ predicate on the "reservation_key" field.
func ReservationKeyNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldReservationKey, v))
}

// ReservationKeyIn applies the In predicate on the "reservation_key" field.
func ReservationKeyIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldReservationKey, vs...))
}

// ReservationKeyNotIn applies the NotIn predicate on the "reservation_key" field.
func ReservationKeyNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldReservationKey, vs...))
}

// ReservationKeyGT applies the GT predicate on the "reservation_key" field.
func ReservationKeyGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldReservationKey, v))
}

// ReservationKeyGTE applies the GTE predicate on the "reservation_key" field.
func ReservationKeyGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldReservationKey, v))
}

// ReservationKeyLT applies the LT predicate on the "reservation_key" field.
func ReservationKeyLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldReservationKey, v))
}

// ReservationKeyLTE applies the LTE predicate on the "reservation_key" field.
func ReservationKeyLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldReservationKey, v))
}

// ReservationKeyContains applies the Contains predicate on the "reservation_key" field.
func ReservationKeyContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldReservationKey, v))
}

// ReservationKeyHasPrefix applies the HasPrefix predicate on the "reservation_key" field.
func ReservationKeyHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldReservationKey, v))
}

// ReservationKeyHasSuffix applies the HasSuffix predicate on the "reservation_key" field.
func ReservationKeyHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldReservationKey, v))
}

// ReservationKeyEqualFold applies the EqualFold predicate on the "reservation_key" field.
func ReservationKeyEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldReservationKey, v))
}

// ReservationKeyContainsFold applies the ContainsFold predicate on the "reservation_key" field.
func ReservationKeyContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldReservationKey, v))
}

// InvoiceIDEQ applies the EQ predicate on the "invoice_id" field.
func InvoiceIDEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldInvoiceID, v))
}

// InvoiceIDNEQ applies the NEQ predicate on the "invoice_id" field.
func InvoiceIDNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldInvoiceID, v))
}

// InvoiceIDIn applies the In predicate on the "invoice_id" field.
func InvoiceIDIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldInvoiceID, vs...))
}

// InvoiceIDNotIn applies the NotIn predicate on the "invoice_id" field.
func InvoiceIDNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldInvoiceID, vs...))
}

// InvoiceIDGT applies the GT predicate on the "invoice_id" field.
func InvoiceIDGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldInvoiceID, v))
}

// InvoiceIDGTE applies the GTE predicate on the "invoice_id" field.
func InvoiceIDGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldInvoiceID, v))
}

// InvoiceIDLT applies the LT predicate on the "invoice_id" field.
func InvoiceIDLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldInvoiceID, v))
}

// InvoiceIDLTE applies the LTE predicate on the "invoice_id" field.
func InvoiceIDLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldInvoiceID, v))
}

// InvoiceIDContains applies the Contains predicate on the "invoice_id" field.
func InvoiceIDContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldInvoiceID, v))
}

// InvoiceIDHasPrefix applies the HasPrefix predicate on the "invoice_id" field.
func InvoiceIDHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldInvoiceID, v))
}

// InvoiceIDHasSuffix applies the HasSuffix predicate on the "invoice_id" field.
func InvoiceIDHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldInvoiceID, v))
}

// InvoiceIDIsNil applies the IsNil predicate on the "invoice_id" field.
func InvoiceIDIsNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIsNull(FieldInvoiceID))
}

// InvoiceIDNotNil applies the NotNil predicate on the "invoice_id" field.
func InvoiceIDNotNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotNull(FieldInvoiceID))
}

// InvoiceIDEqualFold applies the EqualFold predicate on the "invoice_id" field.
func InvoiceIDEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldInvoiceID, v))
}

// InvoiceIDContainsFold applies the ContainsFold predicate on the "invoice_id" field.
func InvoiceIDContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldInvoiceID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotNull(FieldCustomerID))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldCustomerID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldCreatedAt, v))
}

// BoundAtEQ applies the EQ predicate on the "bound_at" field.
func BoundAtEQ(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldEQ(FieldBoundAt, v))
}

// BoundAtNEQ applies the NEQ predicate on the "bound_at" field.
func BoundAtNEQ(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNEQ(FieldBoundAt, v))
}

// BoundAtIn applies the In predicate on the "bound_at" field.
func BoundAtIn(vs ...time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIn(FieldBoundAt, vs...))
}

// BoundAtNotIn applies the NotIn predicate on the "bound_at" field.
func BoundAtNotIn(vs ...time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotIn(FieldBoundAt, vs...))
}

// BoundAtGT applies the GT predicate on the "bound_at" field.
func BoundAtGT(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGT(FieldBoundAt, v))
}

// BoundAtGTE applies the GTE predicate on the "bound_at" field.
func BoundAtGTE(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldGTE(FieldBoundAt, v))
}

// BoundAtLT applies the LT predicate on the "bound_at" field.
func BoundAtLT(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLT(FieldBoundAt, v))
}

// BoundAtLTE applies the LTE predicate on the "bound_at" field.
func BoundAtLTE(v time.Time) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldLTE(FieldBoundAt, v))
}

// BoundAtIsNil applies the IsNil predicate on the "bound_at" field.
func BoundAtIsNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldIsNull(FieldBoundAt))
}

// BoundAtNotNil applies the NotNil predicate on the "bound_at" field.
func BoundAtNotNil() predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.FieldNotNull(FieldBoundAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoicePublicReference) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoicePublicReference) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoicePublicReference) predicate.InvoicePublicReference {
	return predicate.InvoicePublicReference(sql.NotPredicates(p))
}
