// Code generated by ent, DO NOT EDIT.

package invoicereferencealias

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invoicereferencealias type in the database.
	Label = "invoice_reference_alias"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldPublicReference holds the string denoting the public_reference field in the database.
	FieldPublicReference = "public_reference"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldNormalizedAlias holds the string denoting the normalized_alias field in the database.
	FieldNormalizedAlias = "normalized_alias"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the invoicereferencealias in the database.
	Table = "invoice_reference_alias"
)

// Columns holds all SQL columns for invoicereferencealias fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEnvironmentID,
	FieldPublicReference,
	FieldAlias,
	FieldNormalizedAlias,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// EnvironmentIDValidator is a validator for the "environment_id" field. It is called by the builders before save.
	EnvironmentIDValidator func(string) error
	// PublicReferenceValidator is a validator for the "public_reference" field. It is called by the builders before save.
	PublicReferenceValidator func(string) error
	// AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	AliasValidator func(string) error
	// NormalizedAliasValidator is a validator for the "normalized_alias" field. It is called by the builders before save.
	NormalizedAliasValidator func(string) error
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the InvoiceReferenceAlias queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByPublicReference orders the results by the public_reference field.
func ByPublicReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicReference, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByNormalizedAlias orders the results by the normalized_alias field.
func ByNormalizedAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedAlias, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
