// Code generated by ent, DO NOT EDIT.

package invoicereferencealias

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldTenantID, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldEnvironmentID, v))
}

// PublicReference applies equality check predicate on the "public_reference" field. It's identical to PublicReferenceEQ.
func PublicReference(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldPublicReference, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldAlias, v))
}

// NormalizedAlias applies equality check predicate on the "normalized_alias" field. It's identical to NormalizedAliasEQ.
func NormalizedAlias(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldNormalizedAlias, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldTenantID, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// PublicReferenceEQ applies the EQ predicate on the "public_reference" field.
func PublicReferenceEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldPublicReference, v))
}

// PublicReferenceNEQ applies the NEQ predicate on the "public_reference" field.
func PublicReferenceNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldPublicReference, v))
}

// PublicReferenceIn applies the In predicate on the "public_reference" field.
func PublicReferenceIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldPublicReference, vs...))
}

// PublicReferenceNotIn applies the NotIn predicate on the "public_reference" field.
func PublicReferenceNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldPublicReference, vs...))
}

// PublicReferenceGT applies the GT predicate on the "public_reference" field.
func PublicReferenceGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldPublicReference, v))
}

// PublicReferenceGTE applies the GTE predicate on the "public_reference" field.
func PublicReferenceGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldPublicReference, v))
}

// PublicReferenceLT applies the LT predicate on the "public_reference" field.
func PublicReferenceLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldPublicReference, v))
}

// PublicReferenceLTE applies the LTE predicate on the "public_reference" field.
func PublicReferenceLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldPublicReference, v))
}

// PublicReferenceContains applies the Contains predicate on the "public_reference" field.
func PublicReferenceContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldPublicReference, v))
}

// PublicReferenceHasPrefix applies the HasPrefix predicate on the "public_reference" field.
func PublicReferenceHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldPublicReference, v))
}

// PublicReferenceHasSuffix applies the HasSuffix predicate on the "public_reference" field.
func PublicReferenceHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldPublicReference, v))
}

// PublicReferenceEqualFold applies the EqualFold predicate on the "public_reference" field.
func PublicReferenceEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldPublicReference, v))
}

// PublicReferenceContainsFold applies the ContainsFold predicate on the "public_reference" field.
func PublicReferenceContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldPublicReference, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldAlias, v))
}

// NormalizedAliasEQ applies the EQ predicate on the "normalized_alias" field.
func NormalizedAliasEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldNormalizedAlias, v))
}

// NormalizedAliasNEQ applies the NEQ predicate on the "normalized_alias" field.
func NormalizedAliasNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldNormalizedAlias, v))
}

// NormalizedAliasIn applies the In predicate on the "normalized_alias" field.
func NormalizedAliasIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldNormalizedAlias, vs...))
}

// NormalizedAliasNotIn applies the NotIn predicate on the "normalized_alias" field.
func NormalizedAliasNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldNormalizedAlias, vs...))
}

// NormalizedAliasGT applies the GT predicate on the "normalized_alias" field.
func NormalizedAliasGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldNormalizedAlias, v))
}

// NormalizedAliasGTE applies the GTE predicate on the "normalized_alias" field.
func NormalizedAliasGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldNormalizedAlias, v))
}

// NormalizedAliasLT applies the LT predicate on the "normalized_alias" field.
func NormalizedAliasLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldNormalizedAlias, v))
}

// NormalizedAliasLTE applies the LTE predicate on the "normalized_alias" field.
func NormalizedAliasLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldNormalizedAlias, v))
}

// NormalizedAliasContains applies the Contains predicate on the "normalized_alias" field.
func NormalizedAliasContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldNormalizedAlias, v))
}

// NormalizedAliasHasPrefix applies the HasPrefix predicate on the "normalized_alias" field.
func NormalizedAliasHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldNormalizedAlias, v))
}

// NormalizedAliasHasSuffix applies the HasSuffix predicate on the "normalized_alias" field.
func NormalizedAliasHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldNormalizedAlias, v))
}

// NormalizedAliasEqualFold applies the EqualFold predicate on the "normalized_alias" field.
func NormalizedAliasEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldNormalizedAlias, v))
}

// NormalizedAliasContainsFold applies the ContainsFold predicate on the "normalized_alias" field.
func NormalizedAliasContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldNormalizedAlias, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvoiceReferenceAlias) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvoiceReferenceAlias) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvoiceReferenceAlias) predicate.InvoiceReferenceAlias {
	return predicate.InvoiceReferenceAlias(sql.NotPredicates(p))
}
