// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicereferencealias"
)

// InvoiceReferenceAliasCreate is the builder for creating a InvoiceReferenceAlias entity.
type InvoiceReferenceAliasCreate struct {
	config
	mutation *InvoiceReferenceAliasMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (irac *InvoiceReferenceAliasCreate) SetTenantID(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetTenantID(s)
	return irac
}

// SetEnvironmentID sets the "environment_id" field.
func (irac *InvoiceReferenceAliasCreate) SetEnvironmentID(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetEnvironmentID(s)
	return irac
}

// SetPublicReference sets the "public_reference" field.
func (irac *InvoiceReferenceAliasCreate) SetPublicReference(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetPublicReference(s)
	return irac
}

// SetAlias sets the "alias" field.
func (irac *InvoiceReferenceAliasCreate) SetAlias(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetAlias(s)
	return irac
}

// SetNormalizedAlias sets the "normalized_alias" field.
func (irac *InvoiceReferenceAliasCreate) SetNormalizedAlias(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetNormalizedAlias(s)
	return irac
}

// SetCreatedBy sets the "created_by" field.
func (irac *InvoiceReferenceAliasCreate) SetCreatedBy(s string) *InvoiceReferenceAliasCreate {
	irac.mutation.SetCreatedBy(s)
	return irac
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (irac *InvoiceReferenceAliasCreate) SetNillableCreatedBy(s *string) *InvoiceReferenceAliasCreate {
	if s != nil {
		irac.SetCreatedBy(*s)
	}
	return irac
}

// SetCreatedAt sets the "created_at" field.
func (irac *InvoiceReferenceAliasCreate) SetCreatedAt(t time.Time) *InvoiceReferenceAliasCreate {
	irac.mutation.SetCreatedAt(t)
	return irac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (irac *InvoiceReferenceAliasCreate) SetNillableCreatedAt(t *time.Time) *InvoiceReferenceAliasCreate {
	if t != nil {
		irac.SetCreatedAt(*t)
	}
	return irac
}

// Mutation returns the InvoiceReferenceAliasMutation object of the builder.
func (irac *InvoiceReferenceAliasCreate) Mutation() *InvoiceReferenceAliasMutation {
	return irac.mutation
}

// Save creates the InvoiceReferenceAlias in the database.
func (irac *InvoiceReferenceAliasCreate) Save(ctx context.Context) (*InvoiceReferenceAlias, error) {
	irac.defaults()
	return withHooks(ctx, irac.sqlSave, irac.mutation, irac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (irac *InvoiceReferenceAliasCreate) SaveX(ctx context.Context) *InvoiceReferenceAlias {
	v, err := irac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (irac *InvoiceReferenceAliasCreate) Exec(ctx context.Context) error {
	_, err := irac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (irac *InvoiceReferenceAliasCreate) ExecX(ctx context.Context) {
	if err := irac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (irac *InvoiceReferenceAliasCreate) defaults() {
	if _, ok := irac.mutation.CreatedBy(); !ok {
		v := invoicereferencealias.DefaultCreatedBy
		irac.mutation.SetCreatedBy(v)
	}
	if _, ok := irac.mutation.CreatedAt(); !ok {
		v := invoicereferencealias.DefaultCreatedAt()
		irac.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (irac *InvoiceReferenceAliasCreate) check() error {
	if _, ok := irac.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.tenant_id"`)}
	}
	if v, ok := irac.mutation.TenantID(); ok {
		if err := invoicereferencealias.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceReferenceAlias.tenant_id": %w`, err)}
		}
	}
	if _, ok := irac.mutation.EnvironmentID(); !ok {
		return &ValidationError{Name: "environment_id", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.environment_id"`)}
	}
	if v, ok := irac.mutation.EnvironmentID(); ok {
		if err := invoicereferencealias.EnvironmentIDValidator(v); err != nil {
			return &ValidationError{Name: "environment_id", err: fmt.Errorf(`ent: validator failed for field "InvoiceReferenceAlias.environment_id": %w`, err)}
		}
	}
	if _, ok := irac.mutation.PublicReference(); !ok {
		return &ValidationError{Name: "public_reference", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.public_reference"`)}
	}
	if v, ok := irac.mutation.PublicReference(); ok {
		if err := invoicereferencealias.PublicReferenceValidator(v); err != nil {
			return &ValidationError{Name: "public_reference", err: fmt.Errorf(`ent: validator failed for field "InvoiceReferenceAlias.public_reference": %w`, err)}
		}
	}
	if _, ok := irac.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.alias"`)}
	}
	if v, ok := irac.mutation.Alias(); ok {
		if err := invoicereferencealias.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "InvoiceReferenceAlias.alias": %w`, err)}
		}
	}
	if _, ok := irac.mutation.NormalizedAlias(); !ok {
		return &ValidationError{Name: "normalized_alias", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.normalized_alias"`)}
	}
	if v, ok := irac.mutation.NormalizedAlias(); ok {
		if err := invoicereferencealias.NormalizedAliasValidator(v); err != nil {
			return &ValidationError{Name: "normalized_alias", err: fmt.Errorf(`ent: validator failed for field "InvoiceReferenceAlias.normalized_alias": %w`, err)}
		}
	}
	if _, ok := irac.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.created_by"`)}
	}
	if _, ok := irac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoiceReferenceAlias.created_at"`)}
	}
	return nil
}

func (irac *InvoiceReferenceAliasCreate) sqlSave(ctx context.Context) (*InvoiceReferenceAlias, error) {
	if err := irac.check(); err != nil {
		return nil, err
	}
	_node, _spec := irac.createSpec()
	if err := sqlgraph.CreateNode(ctx, irac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	irac.mutation.id = &_node.ID
	irac.mutation.done = true
	return _node, nil
}

func (irac *InvoiceReferenceAliasCreate) createSpec() (*InvoiceReferenceAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceReferenceAlias{config: irac.config}
		_spec = sqlgraph.NewCreateSpec(invoicereferencealias.Table, sqlgraph.NewFieldSpec(invoicereferencealias.FieldID, field.TypeInt))
	)
	if value, ok := irac.mutation.TenantID(); ok {
		_spec.SetField(invoicereferencealias.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := irac.mutation.EnvironmentID(); ok {
		_spec.SetField(invoicereferencealias.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := irac.mutation.PublicReference(); ok {
		_spec.SetField(invoicereferencealias.FieldPublicReference, field.TypeString, value)
		_node.PublicReference = value
	}
	if value, ok := irac.mutation.Alias(); ok {
		_spec.SetField(invoicereferencealias.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := irac.mutation.NormalizedAlias(); ok {
		_spec.SetField(invoicereferencealias.FieldNormalizedAlias, field.TypeString, value)
		_node.NormalizedAlias = value
	}
	if value, ok := irac.mutation.CreatedBy(); ok {
		_spec.SetField(invoicereferencealias.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := irac.mutation.CreatedAt(); ok {
		_spec.SetField(invoicereferencealias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// InvoiceReferenceAliasCreateBulk is the builder for creating many InvoiceReferenceAlias entities in bulk.
type InvoiceReferenceAliasCreateBulk struct {
	config
	err      error
	builders []*InvoiceReferenceAliasCreate
}

// Save creates the InvoiceReferenceAlias entities in the database.
func (iracb *InvoiceReferenceAliasCreateBulk) Save(ctx context.Context) ([]*InvoiceReferenceAlias, error) {
	if iracb.err != nil {
		return nil, iracb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iracb.builders))
	nodes := make([]*InvoiceReferenceAlias, len(iracb.builders))
	mutators := make([]Mutator, len(iracb.builders))
	for i := range iracb.builders {
		func(i int, root context.Context) {
			builder := iracb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceReferenceAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iracb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iracb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iracb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iracb *InvoiceReferenceAliasCreateBulk) SaveX(ctx context.Context) []*InvoiceReferenceAlias {
	v, err := iracb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iracb *InvoiceReferenceAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := iracb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iracb *InvoiceReferenceAliasCreateBulk) ExecX(ctx context.Context) {
	if err := iracb.Exec(ctx); err != nil {
		panic(err)
	}
}
