// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicepublicreference"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoicePublicReferenceDelete is the builder for deleting a InvoicePublicReference entity.
type InvoicePublicReferenceDelete struct {
	config
	hooks    []Hook
	mutation *InvoicePublicReferenceMutation
}

// Where appends a list predicates to the InvoicePublicReferenceDelete builder.
func (iprd *InvoicePublicReferenceDelete) Where(ps ...predicate.InvoicePublicReference) *InvoicePublicReferenceDelete {
	iprd.mutation.Where(ps...)
	return iprd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iprd *InvoicePublicReferenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, iprd.sqlExec, iprd.mutation, iprd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (iprd *InvoicePublicReferenceDelete) ExecX(ctx context.Context) int {
	n, err := iprd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iprd *InvoicePublicReferenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoicepublicreference.Table, sqlgraph.NewFieldSpec(invoicepublicreference.FieldID, field.TypeInt))
	if ps := iprd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iprd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	iprd.mutation.done = true
	return affected, err
}

// InvoicePublicReferenceDeleteOne is the builder for deleting a single InvoicePublicReference entity.
type InvoicePublicReferenceDeleteOne struct {
	iprd *InvoicePublicReferenceDelete
}

// Where appends a list predicates to the InvoicePublicReferenceDelete builder.
func (iprdo *InvoicePublicReferenceDeleteOne) Where(ps ...predicate.InvoicePublicReference) *InvoicePublicReferenceDeleteOne {
	iprdo.iprd.mutation.Where(ps...)
	return iprdo
}

// Exec executes the deletion query.
func (iprdo *InvoicePublicReferenceDeleteOne) Exec(ctx context.Context) error {
	n, err := iprdo.iprd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoicepublicreference.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iprdo *InvoicePublicReferenceDeleteOne) ExecX(ctx context.Context) {
	if err := iprdo.Exec(ctx); err != nil {
		panic(err)
	}
}
