// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicepublicreference"
)

// InvoicePublicReferenceCreate is the builder for creating a InvoicePublicReference entity.
type InvoicePublicReferenceCreate struct {
	config
	mutation *InvoicePublicReferenceMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (iprc *InvoicePublicReferenceCreate) SetTenantID(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetTenantID(s)
	return iprc
}

// SetEnvironmentID sets the "environment_id" field.
func (iprc *InvoicePublicReferenceCreate) SetEnvironmentID(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetEnvironmentID(s)
	return iprc
}

// SetPublicReference sets the "public_reference" field.
func (iprc *InvoicePublicReferenceCreate) SetPublicReference(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetPublicReference(s)
	return iprc
}

// SetReservationKey sets the "reservation_key" field.
func (iprc *InvoicePublicReferenceCreate) SetReservationKey(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetReservationKey(s)
	return iprc
}

// SetInvoiceID sets the "invoice_id" field.
func (iprc *InvoicePublicReferenceCreate) SetInvoiceID(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetInvoiceID(s)
	return iprc
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (iprc *InvoicePublicReferenceCreate) SetNillableInvoiceID(s *string) *InvoicePublicReferenceCreate {
	if s != nil {
		iprc.SetInvoiceID(*s)
	}
	return iprc
}

// SetCustomerID sets the "customer_id" field.
func (iprc *InvoicePublicReferenceCreate) SetCustomerID(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetCustomerID(s)
	return iprc
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (iprc *InvoicePublicReferenceCreate) SetNillableCustomerID(s *string) *InvoicePublicReferenceCreate {
	if s != nil {
		iprc.SetCustomerID(*s)
	}
	return iprc
}

// SetCreatedBy sets the "created_by" field.
func (iprc *InvoicePublicReferenceCreate) SetCreatedBy(s string) *InvoicePublicReferenceCreate {
	iprc.mutation.SetCreatedBy(s)
	return iprc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (iprc *InvoicePublicReferenceCreate) SetNillableCreatedBy(s *string) *InvoicePublicReferenceCreate {
	if s != nil {
		iprc.SetCreatedBy(*s)
	}
	return iprc
}

// SetCreatedAt sets the "created_at" field.
func (iprc *InvoicePublicReferenceCreate) SetCreatedAt(t time.Time) *InvoicePublicReferenceCreate {
	iprc.mutation.SetCreatedAt(t)
	return iprc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iprc *InvoicePublicReferenceCreate) SetNillableCreatedAt(t *time.Time) *InvoicePublicReferenceCreate {
	if t != nil {
		iprc.SetCreatedAt(*t)
	}
	return iprc
}

// SetBoundAt sets the "bound_at" field.
func (iprc *InvoicePublicReferenceCreate) SetBoundAt(t time.Time) *InvoicePublicReferenceCreate {
	iprc.mutation.SetBoundAt(t)
	return iprc
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (iprc *InvoicePublicReferenceCreate) SetNillableBoundAt(t *time.Time) *InvoicePublicReferenceCreate {
	if t != nil {
		iprc.SetBoundAt(*t)
	}
	return iprc
}

// Mutation returns the InvoicePublicReferenceMutation object of the builder.
func (iprc *InvoicePublicReferenceCreate) Mutation() *InvoicePublicReferenceMutation {
	return iprc.mutation
}

// Save creates the InvoicePublicReference in the database.
func (iprc *InvoicePublicReferenceCreate) Save(ctx context.Context) (*InvoicePublicReference, error) {
	iprc.defaults()
	return withHooks(ctx, iprc.sqlSave, iprc.mutation, iprc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (iprc *InvoicePublicReferenceCreate) SaveX(ctx context.Context) *InvoicePublicReference {
	v, err := iprc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iprc *InvoicePublicReferenceCreate) Exec(ctx context.Context) error {
	_, err := iprc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iprc *InvoicePublicReferenceCreate) ExecX(ctx context.Context) {
	if err := iprc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iprc *InvoicePublicReferenceCreate) defaults() {
	if _, ok := iprc.mutation.CreatedBy(); !ok {
		v := invoicepublicreference.DefaultCreatedBy
		iprc.mutation.SetCreatedBy(v)
	}
	if _, ok := iprc.mutation.CreatedAt(); !ok {
		v := invoicepublicreference.DefaultCreatedAt()
		iprc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iprc *InvoicePublicReferenceCreate) check() error {
	if _, ok := iprc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "InvoicePublicReference.tenant_id"`)}
	}
	if v, ok := iprc.mutation.TenantID(); ok {
		if err := invoicepublicreference.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "InvoicePublicReference.tenant_id": %w`, err)}
		}
	}
	if _, ok := iprc.mutation.EnvironmentID(); !ok {
		return &ValidationError{Name: "environment_id", err: errors.New(`ent: missing required field "InvoicePublicReference.environment_id"`)}
	}
	if v, ok := iprc.mutation.EnvironmentID(); ok {
		if err := invoicepublicreference.EnvironmentIDValidator(v); err != nil {
			return &ValidationError{Name: "environment_id", err: fmt.Errorf(`ent: validator failed for field "InvoicePublicReference.environment_id": %w`, err)}
		}
	}
	if _, ok := iprc.mutation.PublicReference(); !ok {
		return &ValidationError{Name: "public_reference", err: errors.New(`ent: missing required field "InvoicePublicReference.public_reference"`)}
	}
	if v, ok := iprc.mutation.PublicReference(); ok {
		if err := invoicepublicreference.PublicReferenceValidator(v); err != nil {
			return &ValidationError{Name: "public_reference", err: fmt.Errorf(`ent: validator failed for field "InvoicePublicReference.public_reference": %w`, err)}
		}
	}
	if _, ok := iprc.mutation.ReservationKey(); !ok {
		return &ValidationError{Name: "reservation_key", err: errors.New(`ent: missing required field "InvoicePublicReference.reservation_key"`)}
	}
	if v, ok := iprc.mutation.ReservationKey(); ok {
		if err := invoicepublicreference.ReservationKeyValidator(v); err != nil {
			return &ValidationError{Name: "reservation_key", err: fmt.Errorf(`ent: validator failed for field "InvoicePublicReference.reservation_key": %w`, err)}
		}
	}
	if _, ok := iprc.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "InvoicePublicReference.created_by"`)}
	}
	if _, ok := iprc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "InvoicePublicReference.created_at"`)}
	}
	return nil
}

func (iprc *InvoicePublicReferenceCreate) sqlSave(ctx context.Context) (*InvoicePublicReference, error) {
	if err := iprc.check(); err != nil {
		return nil, err
	}
	_node, _spec := iprc.createSpec()
	if err := sqlgraph.CreateNode(ctx, iprc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	iprc.mutation.id = &_node.ID
	iprc.mutation.done = true
	return _node, nil
}

func (iprc *InvoicePublicReferenceCreate) createSpec() (*InvoicePublicReference, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoicePublicReference{config: iprc.config}
		_spec = sqlgraph.NewCreateSpec(invoicepublicreference.Table, sqlgraph.NewFieldSpec(invoicepublicreference.FieldID, field.TypeInt))
	)
	if value, ok := iprc.mutation.TenantID(); ok {
		_spec.SetField(invoicepublicreference.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := iprc.mutation.EnvironmentID(); ok {
		_spec.SetField(invoicepublicreference.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := iprc.mutation.PublicReference(); ok {
		_spec.SetField(invoicepublicreference.FieldPublicReference, field.TypeString, value)
		_node.PublicReference = value
	}
	if value, ok := iprc.mutation.ReservationKey(); ok {
		_spec.SetField(invoicepublicreference.FieldReservationKey, field.TypeString, value)
		_node.ReservationKey = value
	}
	if value, ok := iprc.mutation.InvoiceID(); ok {
		_spec.SetField(invoicepublicreference.FieldInvoiceID, field.TypeString, value)
		_node.InvoiceID = &value
	}
	if value, ok := iprc.mutation.CustomerID(); ok {
		_spec.SetField(invoicepublicreference.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = &value
	}
	if value, ok := iprc.mutation.CreatedBy(); ok {
		_spec.SetField(invoicepublicreference.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := iprc.mutation.CreatedAt(); ok {
		_spec.SetField(invoicepublicreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := iprc.mutation.BoundAt(); ok {
		_spec.SetField(invoicepublicreference.FieldBoundAt, field.TypeTime, value)
		_node.BoundAt = &value
	}
	return _node, _spec
}

// InvoicePublicReferenceCreateBulk is the builder for creating many InvoicePublicReference entities in bulk.
type InvoicePublicReferenceCreateBulk struct {
	config
	err      error
	builders []*InvoicePublicReferenceCreate
}

// Save creates the InvoicePublicReference entities in the database.
func (iprcb *InvoicePublicReferenceCreateBulk) Save(ctx context.Context) ([]*InvoicePublicReference, error) {
	if iprcb.err != nil {
		return nil, iprcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(iprcb.builders))
	nodes := make([]*InvoicePublicReference, len(iprcb.builders))
	mutators := make([]Mutator, len(iprcb.builders))
	for i := range iprcb.builders {
		func(i int, root context.Context) {
			builder := iprcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoicePublicReferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iprcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iprcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iprcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iprcb *InvoicePublicReferenceCreateBulk) SaveX(ctx context.Context) []*InvoicePublicReference {
	v, err := iprcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iprcb *InvoicePublicReferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := iprcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iprcb *InvoicePublicReferenceCreateBulk) ExecX(ctx context.Context) {
	if err := iprcb.Exec(ctx); err != nil {
		panic(err)
	}
}
