// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicepublicreference"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoicePublicReferenceQuery is the builder for querying InvoicePublicReference entities.
type InvoicePublicReferenceQuery struct {
	config
	ctx        *QueryContext
	order      []invoicepublicreference.OrderOption
	inters     []Interceptor
	predicates []predicate.InvoicePublicReference
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvoicePublicReferenceQuery builder.
func (iprq *InvoicePublicReferenceQuery) Where(ps ...predicate.InvoicePublicReference) *InvoicePublicReferenceQuery {
	iprq.predicates = append(iprq.predicates, ps...)
	return iprq
}

// Limit the number of records to be returned by this query.
func (iprq *InvoicePublicReferenceQuery) Limit(limit int) *InvoicePublicReferenceQuery {
	iprq.ctx.Limit = &limit
	return iprq
}

// Offset to start from.
func (iprq *InvoicePublicReferenceQuery) Offset(offset int) *InvoicePublicReferenceQuery {
	iprq.ctx.Offset = &offset
	return iprq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iprq *InvoicePublicReferenceQuery) Unique(unique bool) *InvoicePublicReferenceQuery {
	iprq.ctx.Unique = &unique
	return iprq
}

// Order specifies how the records should be ordered.
func (iprq *InvoicePublicReferenceQuery) Order(o ...invoicepublicreference.OrderOption) *InvoicePublicReferenceQuery {
	iprq.order = append(iprq.order, o...)
	return iprq
}

// First returns the first InvoicePublicReference entity from the query.
// Returns a *NotFoundError when no InvoicePublicReference was found.
func (iprq *InvoicePublicReferenceQuery) First(ctx context.Context) (*InvoicePublicReference, error) {
	nodes, err := iprq.Limit(1).All(setContextOp(ctx, iprq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{invoicepublicreference.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) FirstX(ctx context.Context) *InvoicePublicReference {
	node, err := iprq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InvoicePublicReference ID from the query.
// Returns a *NotFoundError when no InvoicePublicReference ID was found.
func (iprq *InvoicePublicReferenceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iprq.Limit(1).IDs(setContextOp(ctx, iprq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{invoicepublicreference.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) FirstIDX(ctx context.Context) int {
	id, err := iprq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InvoicePublicReference entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InvoicePublicReference entity is found.
// Returns a *NotFoundError when no InvoicePublicReference entities are found.
func (iprq *InvoicePublicReferenceQuery) Only(ctx context.Context) (*InvoicePublicReference, error) {
	nodes, err := iprq.Limit(2).All(setContextOp(ctx, iprq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{invoicepublicreference.Label}
	default:
		return nil, &NotSingularError{invoicepublicreference.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) OnlyX(ctx context.Context) *InvoicePublicReference {
	node, err := iprq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InvoicePublicReference ID in the query.
// Returns a *NotSingularError when more than one InvoicePublicReference ID is found.
// Returns a *NotFoundError when no entities are found.
func (iprq *InvoicePublicReferenceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iprq.Limit(2).IDs(setContextOp(ctx, iprq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{invoicepublicreference.Label}
	default:
		err = &NotSingularError{invoicepublicreference.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) OnlyIDX(ctx context.Context) int {
	id, err := iprq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InvoicePublicReferences.
func (iprq *InvoicePublicReferenceQuery) All(ctx context.Context) ([]*InvoicePublicReference, error) {
	ctx = setContextOp(ctx, iprq.ctx, ent.OpQueryAll)
	if err := iprq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InvoicePublicReference, *InvoicePublicReferenceQuery]()
	return withInterceptors[[]*InvoicePublicReference](ctx, iprq, qr, iprq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) AllX(ctx context.Context) []*InvoicePublicReference {
	nodes, err := iprq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InvoicePublicReference IDs.
func (iprq *InvoicePublicReferenceQuery) IDs(ctx context.Context) (ids []int, err error) {
	if iprq.ctx.Unique == nil && iprq.path != nil {
		iprq.Unique(true)
	}
	ctx = setContextOp(ctx, iprq.ctx, ent.OpQueryIDs)
	if err = iprq.Select(invoicepublicreference.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) IDsX(ctx context.Context) []int {
	ids, err := iprq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iprq *InvoicePublicReferenceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iprq.ctx, ent.OpQueryCount)
	if err := iprq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iprq, querierCount[*InvoicePublicReferenceQuery](), iprq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) CountX(ctx context.Context) int {
	count, err := iprq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iprq *InvoicePublicReferenceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iprq.ctx, ent.OpQueryExist)
	switch _, err := iprq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iprq *InvoicePublicReferenceQuery) ExistX(ctx context.Context) bool {
	exist, err := iprq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvoicePublicReferenceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iprq *InvoicePublicReferenceQuery) Clone() *InvoicePublicReferenceQuery {
	if iprq == nil {
		return nil
	}
	return &InvoicePublicReferenceQuery{
		config:     iprq.config,
		ctx:        iprq.ctx.Clone(),
		order:      append([]invoicepublicreference.OrderOption{}, iprq.order...),
		inters:     append([]Interceptor{}, iprq.inters...),
		predicates: append([]predicate.InvoicePublicReference{}, iprq.predicates...),
		// clone intermediate query.
		sql:  iprq.sql.Clone(),
		path: iprq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InvoicePublicReference.Query().
//		GroupBy(invoicepublicreference.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iprq *InvoicePublicReferenceQuery) GroupBy(field string, fields ...string) *InvoicePublicReferenceGroupBy {
	iprq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InvoicePublicReferenceGroupBy{build: iprq}
	grbuild.flds = &iprq.ctx.Fields
	grbuild.label = invoicepublicreference.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.InvoicePublicReference.Query().
//		Select(invoicepublicreference.FieldTenantID).
//		Scan(ctx, &v)
func (iprq *InvoicePublicReferenceQuery) Select(fields ...string) *InvoicePublicReferenceSelect {
	iprq.ctx.Fields = append(iprq.ctx.Fields, fields...)
	sbuild := &InvoicePublicReferenceSelect{InvoicePublicReferenceQuery: iprq}
	sbuild.label = invoicepublicreference.Label
	sbuild.flds, sbuild.scan = &iprq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InvoicePublicReferenceSelect configured with the given aggregations.
func (iprq *InvoicePublicReferenceQuery) Aggregate(fns ...AggregateFunc) *InvoicePublicReferenceSelect {
	return iprq.Select().Aggregate(fns...)
}

func (iprq *InvoicePublicReferenceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iprq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iprq); err != nil {
				return err
			}
		}
	}
	for _, f := range iprq.ctx.Fields {
		if !invoicepublicreference.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iprq.path != nil {
		prev, err := iprq.path(ctx)
		if err != nil {
			return err
		}
		iprq.sql = prev
	}
	return nil
}

func (iprq *InvoicePublicReferenceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InvoicePublicReference, error) {
	var (
		nodes = []*InvoicePublicReference{}
		_spec = iprq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InvoicePublicReference).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InvoicePublicReference{config: iprq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iprq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (iprq *InvoicePublicReferenceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iprq.querySpec()
	_spec.Node.Columns = iprq.ctx.Fields
	if len(iprq.ctx.Fields) > 0 {
		_spec.Unique = iprq.ctx.Unique != nil && *iprq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iprq.driver, _spec)
}

func (iprq *InvoicePublicReferenceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(invoicepublicreference.Table, invoicepublicreference.Columns, sqlgraph.NewFieldSpec(invoicepublicreference.FieldID, field.TypeInt))
	_spec.From = iprq.sql
	if unique := iprq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iprq.path != nil {
		_spec.Unique = true
	}
	if fields := iprq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicepublicreference.FieldID)
		for i := range fields {
			if fields[i] != invoicepublicreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iprq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iprq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iprq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iprq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iprq *InvoicePublicReferenceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iprq.driver.Dialect())
	t1 := builder.Table(invoicepublicreference.Table)
	columns := iprq.ctx.Fields
	if len(columns) == 0 {
		columns = invoicepublicreference.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iprq.sql != nil {
		selector = iprq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iprq.ctx.Unique != nil && *iprq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iprq.predicates {
		p(selector)
	}
	for _, p := range iprq.order {
		p(selector)
	}
	if offset := iprq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iprq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InvoicePublicReferenceGroupBy is the group-by builder for InvoicePublicReference entities.
type InvoicePublicReferenceGroupBy struct {
	selector
	build *InvoicePublicReferenceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iprgb *InvoicePublicReferenceGroupBy) Aggregate(fns ...AggregateFunc) *InvoicePublicReferenceGroupBy {
	iprgb.fns = append(iprgb.fns, fns...)
	return iprgb
}

// Scan applies the selector query and scans the result into the given value.
func (iprgb *InvoicePublicReferenceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iprgb.build.ctx, ent.OpQueryGroupBy)
	if err := iprgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoicePublicReferenceQuery, *InvoicePublicReferenceGroupBy](ctx, iprgb.build, iprgb, iprgb.build.inters, v)
}

func (iprgb *InvoicePublicReferenceGroupBy) sqlScan(ctx context.Context, root *InvoicePublicReferenceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(iprgb.fns))
	for _, fn := range iprgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*iprgb.flds)+len(iprgb.fns))
		for _, f := range *iprgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*iprgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iprgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InvoicePublicReferenceSelect is the builder for selecting fields of InvoicePublicReference entities.
type InvoicePublicReferenceSelect struct {
	*InvoicePublicReferenceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (iprs *InvoicePublicReferenceSelect) Aggregate(fns ...AggregateFunc) *InvoicePublicReferenceSelect {
	iprs.fns = append(iprs.fns, fns...)
	return iprs
}

// Scan applies the selector query and scans the result into the given value.
func (iprs *InvoicePublicReferenceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iprs.ctx, ent.OpQuerySelect)
	if err := iprs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoicePublicReferenceQuery, *InvoicePublicReferenceSelect](ctx, iprs.InvoicePublicReferenceQuery, iprs, iprs.inters, v)
}

func (iprs *InvoicePublicReferenceSelect) sqlScan(ctx context.Context, root *InvoicePublicReferenceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(iprs.fns))
	for _, fn := range iprs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*iprs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iprs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
