// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicepublicreference"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoicePublicReferenceUpdate is the builder for updating InvoicePublicReference entities.
type InvoicePublicReferenceUpdate struct {
	config
	hooks    []Hook
	mutation *InvoicePublicReferenceMutation
}

// Where appends a list predicates to the InvoicePublicReferenceUpdate builder.
func (ipru *InvoicePublicReferenceUpdate) Where(ps ...predicate.InvoicePublicReference) *InvoicePublicReferenceUpdate {
	ipru.mutation.Where(ps...)
	return ipru
}

// SetInvoiceID sets the "invoice_id" field.
func (ipru *InvoicePublicReferenceUpdate) SetInvoiceID(s string) *InvoicePublicReferenceUpdate {
	ipru.mutation.SetInvoiceID(s)
	return ipru
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (ipru *InvoicePublicReferenceUpdate) SetNillableInvoiceID(s *string) *InvoicePublicReferenceUpdate {
	if s != nil {
		ipru.SetInvoiceID(*s)
	}
	return ipru
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (ipru *InvoicePublicReferenceUpdate) ClearInvoiceID() *InvoicePublicReferenceUpdate {
	ipru.mutation.ClearInvoiceID()
	return ipru
}

// SetCustomerID sets the "customer_id" field.
func (ipru *InvoicePublicReferenceUpdate) SetCustomerID(s string) *InvoicePublicReferenceUpdate {
	ipru.mutation.SetCustomerID(s)
	return ipru
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (ipru *InvoicePublicReferenceUpdate) SetNillableCustomerID(s *string) *InvoicePublicReferenceUpdate {
	if s != nil {
		ipru.SetCustomerID(*s)
	}
	return ipru
}

// ClearCustomerID clears the value of the "customer_id" field.
func (ipru *InvoicePublicReferenceUpdate) ClearCustomerID() *InvoicePublicReferenceUpdate {
	ipru.mutation.ClearCustomerID()
	return ipru
}

// SetBoundAt sets the "bound_at" field.
func (ipru *InvoicePublicReferenceUpdate) SetBoundAt(t time.Time) *InvoicePublicReferenceUpdate {
	ipru.mutation.SetBoundAt(t)
	return ipru
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (ipru *InvoicePublicReferenceUpdate) SetNillableBoundAt(t *time.Time) *InvoicePublicReferenceUpdate {
	if t != nil {
		ipru.SetBoundAt(*t)
	}
	return ipru
}

// ClearBoundAt clears the value of the "bound_at" field.
func (ipru *InvoicePublicReferenceUpdate) ClearBoundAt() *InvoicePublicReferenceUpdate {
	ipru.mutation.ClearBoundAt()
	return ipru
}

// Mutation returns the InvoicePublicReferenceMutation object of the builder.
func (ipru *InvoicePublicReferenceUpdate) Mutation() *InvoicePublicReferenceMutation {
	return ipru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ipru *InvoicePublicReferenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ipru.sqlSave, ipru.mutation, ipru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ipru *InvoicePublicReferenceUpdate) SaveX(ctx context.Context) int {
	affected, err := ipru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ipru *InvoicePublicReferenceUpdate) Exec(ctx context.Context) error {
	_, err := ipru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipru *InvoicePublicReferenceUpdate) ExecX(ctx context.Context) {
	if err := ipru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ipru *InvoicePublicReferenceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicepublicreference.Table, invoicepublicreference.Columns, sqlgraph.NewFieldSpec(invoicepublicreference.FieldID, field.TypeInt))
	if ps := ipru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ipru.mutation.InvoiceID(); ok {
		_spec.SetField(invoicepublicreference.FieldInvoiceID, field.TypeString, value)
	}
	if ipru.mutation.InvoiceIDCleared() {
		_spec.ClearField(invoicepublicreference.FieldInvoiceID, field.TypeString)
	}
	if value, ok := ipru.mutation.CustomerID(); ok {
		_spec.SetField(invoicepublicreference.FieldCustomerID, field.TypeString, value)
	}
	if ipru.mutation.CustomerIDCleared() {
		_spec.ClearField(invoicepublicreference.FieldCustomerID, field.TypeString)
	}
	if value, ok := ipru.mutation.BoundAt(); ok {
		_spec.SetField(invoicepublicreference.FieldBoundAt, field.TypeTime, value)
	}
	if ipru.mutation.BoundAtCleared() {
		_spec.ClearField(invoicepublicreference.FieldBoundAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ipru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicepublicreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ipru.mutation.done = true
	return n, nil
}

// InvoicePublicReferenceUpdateOne is the builder for updating a single InvoicePublicReference entity.
type InvoicePublicReferenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoicePublicReferenceMutation
}

// SetInvoiceID sets the "invoice_id" field.
func (ipruo *InvoicePublicReferenceUpdateOne) SetInvoiceID(s string) *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.SetInvoiceID(s)
	return ipruo
}

// SetNillableInvoiceID sets the "invoice_id" field if the given value is not nil.
func (ipruo *InvoicePublicReferenceUpdateOne) SetNillableInvoiceID(s *string) *InvoicePublicReferenceUpdateOne {
	if s != nil {
		ipruo.SetInvoiceID(*s)
	}
	return ipruo
}

// ClearInvoiceID clears the value of the "invoice_id" field.
func (ipruo *InvoicePublicReferenceUpdateOne) ClearInvoiceID() *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.ClearInvoiceID()
	return ipruo
}

// SetCustomerID sets the "customer_id" field.
func (ipruo *InvoicePublicReferenceUpdateOne) SetCustomerID(s string) *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.SetCustomerID(s)
	return ipruo
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (ipruo *InvoicePublicReferenceUpdateOne) SetNillableCustomerID(s *string) *InvoicePublicReferenceUpdateOne {
	if s != nil {
		ipruo.SetCustomerID(*s)
	}
	return ipruo
}

// ClearCustomerID clears the value of the "customer_id" field.
func (ipruo *InvoicePublicReferenceUpdateOne) ClearCustomerID() *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.ClearCustomerID()
	return ipruo
}

// SetBoundAt sets the "bound_at" field.
func (ipruo *InvoicePublicReferenceUpdateOne) SetBoundAt(t time.Time) *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.SetBoundAt(t)
	return ipruo
}

// SetNillableBoundAt sets the "bound_at" field if the given value is not nil.
func (ipruo *InvoicePublicReferenceUpdateOne) SetNillableBoundAt(t *time.Time) *InvoicePublicReferenceUpdateOne {
	if t != nil {
		ipruo.SetBoundAt(*t)
	}
	return ipruo
}

// ClearBoundAt clears the value of the "bound_at" field.
func (ipruo *InvoicePublicReferenceUpdateOne) ClearBoundAt() *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.ClearBoundAt()
	return ipruo
}

// Mutation returns the InvoicePublicReferenceMutation object of the builder.
func (ipruo *InvoicePublicReferenceUpdateOne) Mutation() *InvoicePublicReferenceMutation {
	return ipruo.mutation
}

// Where appends a list predicates to the InvoicePublicReferenceUpdate builder.
func (ipruo *InvoicePublicReferenceUpdateOne) Where(ps ...predicate.InvoicePublicReference) *InvoicePublicReferenceUpdateOne {
	ipruo.mutation.Where(ps...)
	return ipruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ipruo *InvoicePublicReferenceUpdateOne) Select(field string, fields ...string) *InvoicePublicReferenceUpdateOne {
	ipruo.fields = append([]string{field}, fields...)
	return ipruo
}

// Save executes the query and returns the updated InvoicePublicReference entity.
func (ipruo *InvoicePublicReferenceUpdateOne) Save(ctx context.Context) (*InvoicePublicReference, error) {
	return withHooks(ctx, ipruo.sqlSave, ipruo.mutation, ipruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ipruo *InvoicePublicReferenceUpdateOne) SaveX(ctx context.Context) *InvoicePublicReference {
	node, err := ipruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ipruo *InvoicePublicReferenceUpdateOne) Exec(ctx context.Context) error {
	_, err := ipruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ipruo *InvoicePublicReferenceUpdateOne) ExecX(ctx context.Context) {
	if err := ipruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ipruo *InvoicePublicReferenceUpdateOne) sqlSave(ctx context.Context) (_node *InvoicePublicReference, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicepublicreference.Table, invoicepublicreference.Columns, sqlgraph.NewFieldSpec(invoicepublicreference.FieldID, field.TypeInt))
	id, ok := ipruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoicePublicReference.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ipruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicepublicreference.FieldID)
		for _, f := range fields {
			if !invoicepublicreference.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicepublicreference.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ipruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ipruo.mutation.InvoiceID(); ok {
		_spec.SetField(invoicepublicreference.FieldInvoiceID, field.TypeString, value)
	}
	if ipruo.mutation.InvoiceIDCleared() {
		_spec.ClearField(invoicepublicreference.FieldInvoiceID, field.TypeString)
	}
	if value, ok := ipruo.mutation.CustomerID(); ok {
		_spec.SetField(invoicepublicreference.FieldCustomerID, field.TypeString, value)
	}
	if ipruo.mutation.CustomerIDCleared() {
		_spec.ClearField(invoicepublicreference.FieldCustomerID, field.TypeString)
	}
	if value, ok := ipruo.mutation.BoundAt(); ok {
		_spec.SetField(invoicepublicreference.FieldBoundAt, field.TypeTime, value)
	}
	if ipruo.mutation.BoundAtCleared() {
		_spec.ClearField(invoicepublicreference.FieldBoundAt, field.TypeTime)
	}
	_node = &InvoicePublicReference{config: ipruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ipruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicepublicreference.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ipruo.mutation.done = true
	return _node, nil
}
