// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicereferencealias"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoiceReferenceAliasDelete is the builder for deleting a InvoiceReferenceAlias entity.
type InvoiceReferenceAliasDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceReferenceAliasMutation
}

// Where appends a list predicates to the InvoiceReferenceAliasDelete builder.
func (irad *InvoiceReferenceAliasDelete) Where(ps ...predicate.InvoiceReferenceAlias) *InvoiceReferenceAliasDelete {
	irad.mutation.Where(ps...)
	return irad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (irad *InvoiceReferenceAliasDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, irad.sqlExec, irad.mutation, irad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (irad *InvoiceReferenceAliasDelete) ExecX(ctx context.Context) int {
	n, err := irad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (irad *InvoiceReferenceAliasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(invoicereferencealias.Table, sqlgraph.NewFieldSpec(invoicereferencealias.FieldID, field.TypeInt))
	if ps := irad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, irad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	irad.mutation.done = true
	return affected, err
}

// InvoiceReferenceAliasDeleteOne is the builder for deleting a single InvoiceReferenceAlias entity.
type InvoiceReferenceAliasDeleteOne struct {
	irad *InvoiceReferenceAliasDelete
}

// Where appends a list predicates to the InvoiceReferenceAliasDelete builder.
func (irado *InvoiceReferenceAliasDeleteOne) Where(ps ...predicate.InvoiceReferenceAlias) *InvoiceReferenceAliasDeleteOne {
	irado.irad.mutation.Where(ps...)
	return irado
}

// Exec executes the deletion query.
func (irado *InvoiceReferenceAliasDeleteOne) Exec(ctx context.Context) error {
	n, err := irado.irad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoicereferencealias.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (irado *InvoiceReferenceAliasDeleteOne) ExecX(ctx context.Context) {
	if err := irado.Exec(ctx); err != nil {
		panic(err)
	}
}
