// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicereferencealias"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoiceReferenceAliasQuery is the builder for querying InvoiceReferenceAlias entities.
type InvoiceReferenceAliasQuery struct {
	config
	ctx        *QueryContext
	order      []invoicereferencealias.OrderOption
	inters     []Interceptor
	predicates []predicate.InvoiceReferenceAlias
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvoiceReferenceAliasQuery builder.
func (iraq *InvoiceReferenceAliasQuery) Where(ps ...predicate.InvoiceReferenceAlias) *InvoiceReferenceAliasQuery {
	iraq.predicates = append(iraq.predicates, ps...)
	return iraq
}

// Limit the number of records to be returned by this query.
func (iraq *InvoiceReferenceAliasQuery) Limit(limit int) *InvoiceReferenceAliasQuery {
	iraq.ctx.Limit = &limit
	return iraq
}

// Offset to start from.
func (iraq *InvoiceReferenceAliasQuery) Offset(offset int) *InvoiceReferenceAliasQuery {
	iraq.ctx.Offset = &offset
	return iraq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iraq *InvoiceReferenceAliasQuery) Unique(unique bool) *InvoiceReferenceAliasQuery {
	iraq.ctx.Unique = &unique
	return iraq
}

// Order specifies how the records should be ordered.
func (iraq *InvoiceReferenceAliasQuery) Order(o ...invoicereferencealias.OrderOption) *InvoiceReferenceAliasQuery {
	iraq.order = append(iraq.order, o...)
	return iraq
}

// First returns the first InvoiceReferenceAlias entity from the query.
// Returns a *NotFoundError when no InvoiceReferenceAlias was found.
func (iraq *InvoiceReferenceAliasQuery) First(ctx context.Context) (*InvoiceReferenceAlias, error) {
	nodes, err := iraq.Limit(1).All(setContextOp(ctx, iraq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{invoicereferencealias.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) FirstX(ctx context.Context) *InvoiceReferenceAlias {
	node, err := iraq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InvoiceReferenceAlias ID from the query.
// Returns a *NotFoundError when no InvoiceReferenceAlias ID was found.
func (iraq *InvoiceReferenceAliasQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iraq.Limit(1).IDs(setContextOp(ctx, iraq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{invoicereferencealias.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) FirstIDX(ctx context.Context) int {
	id, err := iraq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InvoiceReferenceAlias entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InvoiceReferenceAlias entity is found.
// Returns a *NotFoundError when no InvoiceReferenceAlias entities are found.
func (iraq *InvoiceReferenceAliasQuery) Only(ctx context.Context) (*InvoiceReferenceAlias, error) {
	nodes, err := iraq.Limit(2).All(setContextOp(ctx, iraq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{invoicereferencealias.Label}
	default:
		return nil, &NotSingularError{invoicereferencealias.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) OnlyX(ctx context.Context) *InvoiceReferenceAlias {
	node, err := iraq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InvoiceReferenceAlias ID in the query.
// Returns a *NotSingularError when more than one InvoiceReferenceAlias ID is found.
// Returns a *NotFoundError when no entities are found.
func (iraq *InvoiceReferenceAliasQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iraq.Limit(2).IDs(setContextOp(ctx, iraq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{invoicereferencealias.Label}
	default:
		err = &NotSingularError{invoicereferencealias.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) OnlyIDX(ctx context.Context) int {
	id, err := iraq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InvoiceReferenceAliasSlice.
func (iraq *InvoiceReferenceAliasQuery) All(ctx context.Context) ([]*InvoiceReferenceAlias, error) {
	ctx = setContextOp(ctx, iraq.ctx, ent.OpQueryAll)
	if err := iraq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InvoiceReferenceAlias, *InvoiceReferenceAliasQuery]()
	return withInterceptors[[]*InvoiceReferenceAlias](ctx, iraq, qr, iraq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) AllX(ctx context.Context) []*InvoiceReferenceAlias {
	nodes, err := iraq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InvoiceReferenceAlias IDs.
func (iraq *InvoiceReferenceAliasQuery) IDs(ctx context.Context) (ids []int, err error) {
	if iraq.ctx.Unique == nil && iraq.path != nil {
		iraq.Unique(true)
	}
	ctx = setContextOp(ctx, iraq.ctx, ent.OpQueryIDs)
	if err = iraq.Select(invoicereferencealias.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) IDsX(ctx context.Context) []int {
	ids, err := iraq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iraq *InvoiceReferenceAliasQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iraq.ctx, ent.OpQueryCount)
	if err := iraq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iraq, querierCount[*InvoiceReferenceAliasQuery](), iraq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) CountX(ctx context.Context) int {
	count, err := iraq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iraq *InvoiceReferenceAliasQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iraq.ctx, ent.OpQueryExist)
	switch _, err := iraq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iraq *InvoiceReferenceAliasQuery) ExistX(ctx context.Context) bool {
	exist, err := iraq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvoiceReferenceAliasQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iraq *InvoiceReferenceAliasQuery) Clone() *InvoiceReferenceAliasQuery {
	if iraq == nil {
		return nil
	}
	return &InvoiceReferenceAliasQuery{
		config:     iraq.config,
		ctx:        iraq.ctx.Clone(),
		order:      append([]invoicereferencealias.OrderOption{}, iraq.order...),
		inters:     append([]Interceptor{}, iraq.inters...),
		predicates: append([]predicate.InvoiceReferenceAlias{}, iraq.predicates...),
		// clone intermediate query.
		sql:  iraq.sql.Clone(),
		path: iraq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InvoiceReferenceAlias.Query().
//		GroupBy(invoicereferencealias.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iraq *InvoiceReferenceAliasQuery) GroupBy(field string, fields ...string) *InvoiceReferenceAliasGroupBy {
	iraq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InvoiceReferenceAliasGroupBy{build: iraq}
	grbuild.flds = &iraq.ctx.Fields
	grbuild.label = invoicereferencealias.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID string `json:"tenant_id,omitempty"`
//	}
//
//	client.InvoiceReferenceAlias.Query().
//		Select(invoicereferencealias.FieldTenantID).
//		Scan(ctx, &v)
func (iraq *InvoiceReferenceAliasQuery) Select(fields ...string) *InvoiceReferenceAliasSelect {
	iraq.ctx.Fields = append(iraq.ctx.Fields, fields...)
	sbuild := &InvoiceReferenceAliasSelect{InvoiceReferenceAliasQuery: iraq}
	sbuild.label = invoicereferencealias.Label
	sbuild.flds, sbuild.scan = &iraq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InvoiceReferenceAliasSelect configured with the given aggregations.
func (iraq *InvoiceReferenceAliasQuery) Aggregate(fns ...AggregateFunc) *InvoiceReferenceAliasSelect {
	return iraq.Select().Aggregate(fns...)
}

func (iraq *InvoiceReferenceAliasQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iraq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iraq); err != nil {
				return err
			}
		}
	}
	for _, f := range iraq.ctx.Fields {
		if !invoicereferencealias.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iraq.path != nil {
		prev, err := iraq.path(ctx)
		if err != nil {
			return err
		}
		iraq.sql = prev
	}
	return nil
}

func (iraq *InvoiceReferenceAliasQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InvoiceReferenceAlias, error) {
	var (
		nodes = []*InvoiceReferenceAlias{}
		_spec = iraq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InvoiceReferenceAlias).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InvoiceReferenceAlias{config: iraq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iraq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (iraq *InvoiceReferenceAliasQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iraq.querySpec()
	_spec.Node.Columns = iraq.ctx.Fields
	if len(iraq.ctx.Fields) > 0 {
		_spec.Unique = iraq.ctx.Unique != nil && *iraq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iraq.driver, _spec)
}

func (iraq *InvoiceReferenceAliasQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(invoicereferencealias.Table, invoicereferencealias.Columns, sqlgraph.NewFieldSpec(invoicereferencealias.FieldID, field.TypeInt))
	_spec.From = iraq.sql
	if unique := iraq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iraq.path != nil {
		_spec.Unique = true
	}
	if fields := iraq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicereferencealias.FieldID)
		for i := range fields {
			if fields[i] != invoicereferencealias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iraq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iraq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iraq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iraq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iraq *InvoiceReferenceAliasQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iraq.driver.Dialect())
	t1 := builder.Table(invoicereferencealias.Table)
	columns := iraq.ctx.Fields
	if len(columns) == 0 {
		columns = invoicereferencealias.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iraq.sql != nil {
		selector = iraq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iraq.ctx.Unique != nil && *iraq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iraq.predicates {
		p(selector)
	}
	for _, p := range iraq.order {
		p(selector)
	}
	if offset := iraq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iraq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InvoiceReferenceAliasGroupBy is the group-by builder for InvoiceReferenceAlias entities.
type InvoiceReferenceAliasGroupBy struct {
	selector
	build *InvoiceReferenceAliasQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (iragb *InvoiceReferenceAliasGroupBy) Aggregate(fns ...AggregateFunc) *InvoiceReferenceAliasGroupBy {
	iragb.fns = append(iragb.fns, fns...)
	return iragb
}

// Scan applies the selector query and scans the result into the given value.
func (iragb *InvoiceReferenceAliasGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iragb.build.ctx, ent.OpQueryGroupBy)
	if err := iragb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoiceReferenceAliasQuery, *InvoiceReferenceAliasGroupBy](ctx, iragb.build, iragb, iragb.build.inters, v)
}

func (iragb *InvoiceReferenceAliasGroupBy) sqlScan(ctx context.Context, root *InvoiceReferenceAliasQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(iragb.fns))
	for _, fn := range iragb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*iragb.flds)+len(iragb.fns))
		for _, f := range *iragb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*iragb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iragb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InvoiceReferenceAliasSelect is the builder for selecting fields of InvoiceReferenceAlias entities.
type InvoiceReferenceAliasSelect struct {
	*InvoiceReferenceAliasQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (iras *InvoiceReferenceAliasSelect) Aggregate(fns ...AggregateFunc) *InvoiceReferenceAliasSelect {
	iras.fns = append(iras.fns, fns...)
	return iras
}

// Scan applies the selector query and scans the result into the given value.
func (iras *InvoiceReferenceAliasSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, iras.ctx, ent.OpQuerySelect)
	if err := iras.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvoiceReferenceAliasQuery, *InvoiceReferenceAliasSelect](ctx, iras.InvoiceReferenceAliasQuery, iras, iras.inters, v)
}

func (iras *InvoiceReferenceAliasSelect) sqlScan(ctx context.Context, root *InvoiceReferenceAliasQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(iras.fns))
	for _, fn := range iras.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*iras.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := iras.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
