// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/invoicepublicreference"
)

// InvoicePublicReference is the model entity for the InvoicePublicReference schema.
type InvoicePublicReference struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// PublicReference holds the value of the "public_reference" field.
	PublicReference string `json:"public_reference,omitempty"`
	// ReservationKey holds the value of the "reservation_key" field.
	ReservationKey string `json:"reservation_key,omitempty"`
	// InvoiceID holds the value of the "invoice_id" field.
	InvoiceID *string `json:"invoice_id,omitempty"`
	// CustomerID holds the value of the "customer_id" field.
	CustomerID *string `json:"customer_id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt      *time.Time `json:"bound_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoicePublicReference) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicepublicreference.FieldID:
			values[i] = new(sql.NullInt64)
		case invoicepublicreference.FieldTenantID, invoicepublicreference.FieldEnvironmentID, invoicepublicreference.FieldPublicReference, invoicepublicreference.FieldReservationKey, invoicepublicreference.FieldInvoiceID, invoicepublicreference.FieldCustomerID, invoicepublicreference.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case invoicepublicreference.FieldCreatedAt, invoicepublicreference.FieldBoundAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoicePublicReference fields.
func (ipr *InvoicePublicReference) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicepublicreference.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ipr.ID = int(value.Int64)
		case invoicepublicreference.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				ipr.TenantID = value.String
			}
		case invoicepublicreference.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				ipr.EnvironmentID = value.String
			}
		case invoicepublicreference.FieldPublicReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_reference", values[i])
			} else if value.Valid {
				ipr.PublicReference = value.String
			}
		case invoicepublicreference.FieldReservationKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reservation_key", values[i])
			} else if value.Valid {
				ipr.ReservationKey = value.String
			}
		case invoicepublicreference.FieldInvoiceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_id", values[i])
			} else if value.Valid {
				ipr.InvoiceID = new(string)
				*ipr.InvoiceID = value.String
			}
		case invoicepublicreference.FieldCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_id", values[i])
			} else if value.Valid {
				ipr.CustomerID = new(string)
				*ipr.CustomerID = value.String
			}
		case invoicepublicreference.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				ipr.CreatedBy = value.String
			}
		case invoicepublicreference.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ipr.CreatedAt = value.Time
			}
		case invoicepublicreference.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				ipr.BoundAt = new(time.Time)
				*ipr.BoundAt = value.Time
			}
		default:
			ipr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoicePublicReference.
// This includes values selected through modifiers, order, etc.
func (ipr *InvoicePublicReference) Value(name string) (ent.Value, error) {
	return ipr.selectValues.Get(name)
}

// Update returns a builder for updating this InvoicePublicReference.
// Note that you need to call InvoicePublicReference.Unwrap() before calling this method if this InvoicePublicReference
// was returned from a transaction, and the transaction was committed or rolled back.
func (ipr *InvoicePublicReference) Update() *InvoicePublicReferenceUpdateOne {
	return NewInvoicePublicReferenceClient(ipr.config).UpdateOne(ipr)
}

// Unwrap unwraps the InvoicePublicReference entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ipr *InvoicePublicReference) Unwrap() *InvoicePublicReference {
	_tx, ok := ipr.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoicePublicReference is not a transactional entity")
	}
	ipr.config.driver = _tx.drv
	return ipr
}

// String implements the fmt.Stringer.
func (ipr *InvoicePublicReference) String() string {
	var builder strings.Builder
	builder.WriteString("InvoicePublicReference(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ipr.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(ipr.TenantID)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(ipr.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("public_reference=")
	builder.WriteString(ipr.PublicReference)
	builder.WriteString(", ")
	builder.WriteString("reservation_key=")
	builder.WriteString(ipr.ReservationKey)
	builder.WriteString(", ")
	if v := ipr.InvoiceID; v != nil {
		builder.WriteString("invoice_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ipr.CustomerID; v != nil {
		builder.WriteString("customer_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(ipr.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ipr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ipr.BoundAt; v != nil {
		builder.WriteString("bound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// InvoicePublicReferences is a parsable slice of InvoicePublicReference.
type InvoicePublicReferences []*InvoicePublicReference
