// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/invoicereferencealias"
	"github.com/flexprice/flexprice/ent/predicate"
)

// InvoiceReferenceAliasUpdate is the builder for updating InvoiceReferenceAlias entities.
type InvoiceReferenceAliasUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceReferenceAliasMutation
}

// Where appends a list predicates to the InvoiceReferenceAliasUpdate builder.
func (irau *InvoiceReferenceAliasUpdate) Where(ps ...predicate.InvoiceReferenceAlias) *InvoiceReferenceAliasUpdate {
	irau.mutation.Where(ps...)
	return irau
}

// Mutation returns the InvoiceReferenceAliasMutation object of the builder.
func (irau *InvoiceReferenceAliasUpdate) Mutation() *InvoiceReferenceAliasMutation {
	return irau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (irau *InvoiceReferenceAliasUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, irau.sqlSave, irau.mutation, irau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (irau *InvoiceReferenceAliasUpdate) SaveX(ctx context.Context) int {
	affected, err := irau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (irau *InvoiceReferenceAliasUpdate) Exec(ctx context.Context) error {
	_, err := irau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (irau *InvoiceReferenceAliasUpdate) ExecX(ctx context.Context) {
	if err := irau.Exec(ctx); err != nil {
		panic(err)
	}
}

func (irau *InvoiceReferenceAliasUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicereferencealias.Table, invoicereferencealias.Columns, sqlgraph.NewFieldSpec(invoicereferencealias.FieldID, field.TypeInt))
	if ps := irau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, irau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicereferencealias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	irau.mutation.done = true
	return n, nil
}

// InvoiceReferenceAliasUpdateOne is the builder for updating a single InvoiceReferenceAlias entity.
type InvoiceReferenceAliasUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceReferenceAliasMutation
}

// Mutation returns the InvoiceReferenceAliasMutation object of the builder.
func (irauo *InvoiceReferenceAliasUpdateOne) Mutation() *InvoiceReferenceAliasMutation {
	return irauo.mutation
}

// Where appends a list predicates to the InvoiceReferenceAliasUpdate builder.
func (irauo *InvoiceReferenceAliasUpdateOne) Where(ps ...predicate.InvoiceReferenceAlias) *InvoiceReferenceAliasUpdateOne {
	irauo.mutation.Where(ps...)
	return irauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (irauo *InvoiceReferenceAliasUpdateOne) Select(field string, fields ...string) *InvoiceReferenceAliasUpdateOne {
	irauo.fields = append([]string{field}, fields...)
	return irauo
}

// Save executes the query and returns the updated InvoiceReferenceAlias entity.
func (irauo *InvoiceReferenceAliasUpdateOne) Save(ctx context.Context) (*InvoiceReferenceAlias, error) {
	return withHooks(ctx, irauo.sqlSave, irauo.mutation, irauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (irauo *InvoiceReferenceAliasUpdateOne) SaveX(ctx context.Context) *InvoiceReferenceAlias {
	node, err := irauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (irauo *InvoiceReferenceAliasUpdateOne) Exec(ctx context.Context) error {
	_, err := irauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (irauo *InvoiceReferenceAliasUpdateOne) ExecX(ctx context.Context) {
	if err := irauo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (irauo *InvoiceReferenceAliasUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceReferenceAlias, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoicereferencealias.Table, invoicereferencealias.Columns, sqlgraph.NewFieldSpec(invoicereferencealias.FieldID, field.TypeInt))
	id, ok := irauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceReferenceAlias.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := irauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoicereferencealias.FieldID)
		for _, f := range fields {
			if !invoicereferencealias.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoicereferencealias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := irauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &InvoiceReferenceAlias{config: irauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, irauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoicereferencealias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	irauo.mutation.done = true
	return _node, nil
}
