// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/invoicereferencealias"
)

// InvoiceReferenceAlias is the model entity for the InvoiceReferenceAlias schema.
type InvoiceReferenceAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// EnvironmentID holds the value of the "environment_id" field.
	EnvironmentID string `json:"environment_id,omitempty"`
	// PublicReference holds the value of the "public_reference" field.
	PublicReference string `json:"public_reference,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// NormalizedAlias holds the value of the "normalized_alias" field.
	NormalizedAlias string `json:"normalized_alias,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvoiceReferenceAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invoicereferencealias.FieldID:
			values[i] = new(sql.NullInt64)
		case invoicereferencealias.FieldTenantID, invoicereferencealias.FieldEnvironmentID, invoicereferencealias.FieldPublicReference, invoicereferencealias.FieldAlias, invoicereferencealias.FieldNormalizedAlias, invoicereferencealias.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case invoicereferencealias.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvoiceReferenceAlias fields.
func (ira *InvoiceReferenceAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invoicereferencealias.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ira.ID = int(value.Int64)
		case invoicereferencealias.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				ira.TenantID = value.String
			}
		case invoicereferencealias.FieldEnvironmentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment_id", values[i])
			} else if value.Valid {
				ira.EnvironmentID = value.String
			}
		case invoicereferencealias.FieldPublicReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_reference", values[i])
			} else if value.Valid {
				ira.PublicReference = value.String
			}
		case invoicereferencealias.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				ira.Alias = value.String
			}
		case invoicereferencealias.FieldNormalizedAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_alias", values[i])
			} else if value.Valid {
				ira.NormalizedAlias = value.String
			}
		case invoicereferencealias.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				ira.CreatedBy = value.String
			}
		case invoicereferencealias.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ira.CreatedAt = value.Time
			}
		default:
			ira.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvoiceReferenceAlias.
// This includes values selected through modifiers, order, etc.
func (ira *InvoiceReferenceAlias) Value(name string) (ent.Value, error) {
	return ira.selectValues.Get(name)
}

// Update returns a builder for updating this InvoiceReferenceAlias.
// Note that you need to call InvoiceReferenceAlias.Unwrap() before calling this method if this InvoiceReferenceAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (ira *InvoiceReferenceAlias) Update() *InvoiceReferenceAliasUpdateOne {
	return NewInvoiceReferenceAliasClient(ira.config).UpdateOne(ira)
}

// Unwrap unwraps the InvoiceReferenceAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ira *InvoiceReferenceAlias) Unwrap() *InvoiceReferenceAlias {
	_tx, ok := ira.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvoiceReferenceAlias is not a transactional entity")
	}
	ira.config.driver = _tx.drv
	return ira
}

// String implements the fmt.Stringer.
func (ira *InvoiceReferenceAlias) String() string {
	var builder strings.Builder
	builder.WriteString("InvoiceReferenceAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ira.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(ira.TenantID)
	builder.WriteString(", ")
	builder.WriteString("environment_id=")
	builder.WriteString(ira.EnvironmentID)
	builder.WriteString(", ")
	builder.WriteString("public_reference=")
	builder.WriteString(ira.PublicReference)
	builder.WriteString(", ")
	builder.WriteString("alias=")
	builder.WriteString(ira.Alias)
	builder.WriteString(", ")
	builder.WriteString("normalized_alias=")
	builder.WriteString(ira.NormalizedAlias)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(ira.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ira.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InvoiceReferenceAliasSlice is a parsable slice of InvoiceReferenceAlias.
type InvoiceReferenceAliasSlice []*InvoiceReferenceAlias
